---
name: "nextbike"
author: "Jonathan Strickland"

dependencies:
  - base
  - text
  - bytestring
  - aeson
  - servant
  - servant-client
  - servant-client-core
  - http-client-tls
  - http-media

library:
  source-dirs:
    - src

default-extensions:
  - TypeApplications
  - DeriveGeneric
  - DataKinds
  - TypeOperators
  - OverloadedStrings
  - NamedFieldPuns
  - DerivingVia
  - GeneralizedNewtypeDeriving
  - StandaloneDeriving
  - FlexibleInstances
  - MultiParamTypeClasses
